SHELL = /bin/bash

INSTALLCMD = cp -r
SRCDIR1 = .cache/
SRCDIR2 = .config/
SRCDIR3 = .local/
SRCDIR4 = tmp/
SRCSCRIPT = uppies.sh
INSTALLDIR = $(KITTENVIM_DIR)

all:

clean:

install:
	$(INSTALLCMD) $(SRCDIR1) $(INSTALLDIR)$(SRCDIR1)

	$(INSTALLCMD) $(SRCDIR2) $(INSTALLDIR)$(SRCDIR2)

	$(INSTALLCMD) $(SRCDIR3) $(INSTALLDIR)$(SRCDIR3)

	$(INSTALLCMD) $(SRCDIR4) $(INSTALLDIR)$(SRCDIR4)

	$(INSTALLCMD) $(SRCSCRIPT) $(INSTALLDIR)$(SRCSCRIPT)
