SHELL = /bin/bash

INSTALL_DIR_CMD = mkdir
INSTALLCMD = cp -r
SRCDIR1 = .cache/
SRCDIR2 = .config/
SRCDIR3 = .local/
SRCDIR4 = tmp/
SRC = nvim/
SRCSCRIPT = uppies.sh
SRCSCRIPT_CMD = bash
INSTALLDIR = $(HOME)/.config/kittenvim/

RM_CMD = rm -rf

all:
	$(INSTALL_DIR_CMD) $(INSTALLDIR)

	$(INSTALL_DIR_CMD) $(INSTALLDIR)$(SRCDIR1)

	$(INSTALL_DIR_CMD) $(INSTALLDIR)$(SRCDIR2)

	$(INSTALL_DIR_CMD) $(INSTALLDIR)$(SRCDIR3)

	$(INSTALL_DIR_CMD) $(INSTALLDIR)$(SRCDIR4)

	$(INSTALL_DIR_CMD) $(INSTALLDIR)$(SRCDIR2)$(SRC)

clean:
	$(RM_CMD) $(INSTALLDIR)

install:

	$(INSTALLCMD) $(SRC) $(INSTALLDIR)$(SRCDIR2)
	
	$(INSTALLCMD) $(SRCSCRIPT) $(INSTALLDIR)$(SRCSCRIPT)

	$(SRCSCRIPT_CMD) $(INSTALLDIR)$(SRCSCRIPT)
